# Generated by Django 5.2.10 on 2026-02-23 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('event', models.CharField(db_index=True, max_length=256, unique=True)),
                ('prize_id', models.IntegerField(blank=True, help_text='Optional prize reference', null=True)),
                ('readonly', models.BooleanField(default=False, help_text='System-created; admin cannot edit')),
                ('value_type', models.CharField(choices=[('none', 'None'), ('string', 'String'), ('bool', 'Bool'), ('number', 'Number')], default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='groups.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='groups.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_entity_id', models.CharField(blank=True, max_length=256)),
                ('target_entity_id', models.CharField(blank=True, max_length=256)),
                ('value', models.JSONField(blank=True, default=None, null=True)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'user', 'created_at'], name='events_user_event_i_888405_idx')],
            },
        ),
    ]
