# Generated by Django 5.2.10 on 2026-02-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='host_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='max_players',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='match',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='match',
            name='mode',
            field=models.CharField(choices=[('offline', 'Offline'), ('real-time', 'Real Time'), ('turn-based', 'Turn Based')], default='real-time', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='scene_slug',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
