# Generated by Django 5.2.10 on 2026-02-23 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_add_match_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_id', models.IntegerField()),
                ('inviter_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='games.match')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('match', 'invitee_id')},
            },
        ),
    ]
