# Generated by Django 5.2.10 on 2026-02-23 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('access', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('content_url', models.URLField(blank=True, max_length=512)),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Image', 'Image'), ('Video', 'Video'), ('Sound', 'Sound'), ('File', 'File')], default='Text', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='groups.category')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='languages.language')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='content_items', to='groups.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
