# Generated by Django 5.2.10 on 2026-02-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contents',
            field=models.JSONField(blank=True, default=list, help_text='Contents Type: [{key, id}] - content refs e.g. avatar, theme'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(blank=True, db_index=True, max_length=256),
        ),
    ]
